openapi: 3.0.2
info:
  title: 'Vendor Management System'
  version: '1.1'
servers:
  - url: https://vendorms.pythonanywhere.com
paths:
  /api/vendors/:
    get:
      security:
          - TokenAuth: []
      operationId: listVendors
      description: 'Retrieve a list of vendors'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vendor'
          description: ''
      tags:
      - api
    post:
      security:
          - TokenAuth: []
      operationId: createVendor
      description: 'Create a new vendor'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vendor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vendor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vendor'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
      tags:
      - api
  /api/vendors/{id}/:
    get:
      security:
          - TokenAuth: []
      operationId: retrieveVendor
      description: 'Retrieve a specific vendor information'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vendor.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
      tags:
      - api
    put:
      security:
          - TokenAuth: []
      operationId: updateVendor
      description: 'Update a specific vendor information'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vendor.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vendor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vendor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vendor'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
      tags:
      - api
    delete:
      security:
          - TokenAuth: []
      operationId: destroyVendor
      description: 'Delete a specific vendor information'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vendor.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/vendors/{id}/performance/:
    get:
      security:
          - TokenAuth: []
      operationId: performanceVendor
      description: 'Retrieve performance data for a specific vendor'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this vendor.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
      tags:
      - api
  /api/purchase_orders/:
    get:
      security:
          - TokenAuth: []
      operationId: listPurchaseOrders
      description: 'Retrieve a list of purchase orders'
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
          description: ''
      tags:
      - api
    post:
      security:
          - TokenAuth: []
      operationId: createPurchaseOrder
      description: 'Create a new purchase order'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
      tags:
      - api
  /api/purchase_orders/{id}/:
    get:
      security:
          - TokenAuth: []
      operationId: retrievePurchaseOrder
      description: 'Retrieve a specific purchase order information'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this purchase order.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
      tags:
      - api
    put:
      security:
          - TokenAuth: []
      operationId: updatePurchaseOrder
      description: 'Update a specific purchase order information'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this purchase order.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
      tags:
      - api
    delete:
      security:
          - TokenAuth: []
      operationId: destroyPurchaseOrder
      description: 'Delete a specific purchase order'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this purchase order.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/purchase_orders/{id}/acknowledge/:
    post:
      security:
          - TokenAuth: []
      operationId: acknowledgePurchaseOrder
      description: 'Acknowledge a specific purchase order. (Only the vendor to which order is issued can acknowledge the order)'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this purchase order.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quality_rating:
                  type: number
                  nullable: true
                  description: Optional
          
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                quality_rating:
                  type: number
                  nullable: true
                  description: Optional
          multipart/form-data:
            schema:
              
              type: object
              properties:
                quality_rating:
                  type: number
                  nullable: true
                  description: Optional
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: 'Succesfully acknowledged purchase order'
        "401":
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

          description: "Unauthorized. Only reference vendor can acknowledge it"
      tags:
      - api
  /api/login/:
    post:
      operationId: createUserLogin
      description: 'API For login to generate token'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string

          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          content:
            application/json:
              schema: 
                type: object
                properties:
                  success:
                    type: boolean
                  username:
                    type: string
                  email:
                    type: string
                  token:
                    type: string
          description: ''
      tags:
      - api
  /api/register/:
    post:
      operationId: createUserRegister
      description: 'API tp register new user'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password2:
                  type: string
                  description: Confirm Password
                first_name:
                  type: string
                  nullable: true
                  description: Optional
                last_name:
                  type: string
                  nullable: true
                  description: Optional
                vendor_code:
                  type: string
                  nullable: true
                  description: Optional, Vendor Code if user is vendor
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password2:
                  type: string
                  description: Confirm Password
                first_name:
                  type: string
                  nullable: true
                  description: Optional
                last_name:
                  type: string
                  nullable: true
                  description: Optional
                vendor_code:
                  type: string
                  nullable: true
                  description: Optional, Vendor Code if user is vendor
          multipart/form-data:
            schema: 
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password2:
                  type: string
                  description: Confirm Password
                first_name:
                  type: string
                  nullable: true
                  description: Optional
                last_name:
                  type: string
                  nullable: true
                  description: Optional
                vendor_code:
                  type: string
                  nullable: true
                  description: Optional, Vendor Code if user is vendor
      responses:
        '201':
          content:
            application/json:
              schema: 
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string

                  token:
                    type: string
          description: ''
      tags:
      - api
  /api/logout/:
    post:
      security:
          - TokenAuth: []
      operationId: createUserLogout
      description: 'Logout active user or delete token'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: Token
      bearerFormat: Token
  schemas:
    Vendor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        contact_details:
          type: string
        address:
          type: string
        vendor_code:
          type: string
          maxLength: 200
        on_time_delivery_rate:
          type: number
          nullable: true
          description: Optional
        quality_rating_avg:
          type: number
          nullable: true
          description: Optional
        average_response_time:
          type: number
          nullable: true
          description: Optional
        fulfillment_rate:
          type: number
          nullable: true
          description: Optional
      required:
      - name
      - contact_details
      - address
      - vendor_code
    PurchaseOrder:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        items:
          type: object
          description: 'Enter items in JSON format. Example: {"item1": 10, "item2":
            20}'
        po_number:
          type: string
          maxLength: 200
        order_date:
          type: string
          format: date
        delivery_date:
          type: string
          format: date
          nullable: true
          description: Expected or Actual Delivery Date
        quantity:
          type: integer
          readOnly: true
          description: Auto Calculated with items
        status:
          enum:
          - pending
          - completed
          - canceled
          type: string
          description: Enter status of the order
        quality_rating:
          type: number
          nullable: true
          description: Optional
        issue_date:
          type: string
          format: date
          readOnly: true
        acknowledgment_date:
          type: string
          format: date
          nullable: true
          description: Optional
        vendor_reference:
          type: integer
          nullable: true
          description: Enter vendor id
      required:
      - items
      - po_number
      - order_date
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - username
      - password
